### ISSUE TITLE
Can't create a record in TYPO3 7.6

### ISSUE THREAD

**Issue by bandanh** [AOEpeople/TYPO3_RestlerExamples#1]
When I try to create a record in TYPO3 7.6  I  get this error message: 

``` #1437750231: The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7. Please set module[name]=module_name instead of using script=path/to/script.php in your TCA. (More information)```

Replacing ` 'script' => 'wizard_rte.php',` 

with `
                        'module' => [
                            'name' => 'wizard_rte',
                        ],`

in the TCA fixes it.

**Comment by vdespa** [comment]
Thanks for reporting this.

We will soon have a look at it.

**Comment by felixsemmler** [comment]
Sorry for the late response. TYPO3 V7 is no more supported. You can find compatible versions of the [restler_examples](https://extensions.typo3.org/extension/restler_examples) extension for TYPO3 8, 9 and 10 in TER or on [packagist](https://packagist.org/packages/aoe/restler-examples).
