### ISSUE TITLE
TYPO3 8?

### ISSUE THREAD

**Issue by rowild** [AOEpeople/TYPO3_RestlerExamples#2]
Any plans to upgrade the example ext to be compatible with version TYPO3 8 LTS?

**Comment by vdespa** [comment]
Hi Robert, unfortunately we have nothing planned at this point for TYPO3 8. Sorry about that!

We are always welcoming PRs to add support for TYPO3 8 or bug fixes.

**Comment by felixsemmler** [comment]
Sorry for the late response. You can find compatible versions of the restler_examples extension for TYPO3 8, 9 and 10 in [TER](https://extensions.typo3.org/extension/restler_examples) or [packagist](https://packagist.org/packages/aoe/restler-examples).
